// <auto-generated />
namespace TrackingCar.Migrations.TrackingContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MigracionCountryInCity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracionCountryInCity));
        
        string IMigrationMetadata.Id
        {
            get { return "201705231543013_MigracionCountryInCity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
